
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: task_manager_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend 
    container_name: task-manager-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_manager_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      JWT_SECRET: XGyx1yvY9lzxdnGqxz0ice1lanZLba+EoMDOcvPUnHA=
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: task-manager-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
