#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql_container
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: task_manager_db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  backend:
#    build: .
#    container_name: backend_container
#    restart: always
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_manager_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8080:8080"
#
#volumes:
#  mysql_data:
