## Use a lightweight OpenJDK 17 image
#FROM eclipse-temurin:17-jdk-alpine
#
## Set the working directory inside the container
#WORKDIR /app
#
## Copy the built JAR file into the container
#COPY target/Backend-0.0.1-SNAPSHOT.jar app.jar
#
## Expose port 8080
#EXPOSE 8080
#
## Run the application
#ENTRYPOINT ["java", "-jar", "app.jar"]
